### ISSUE TITLE
Support for erubis?

### ISSUE THREAD

**Issue by njh** [foca/sinatra-content-for#3]
Hello,

I have just tried switching my Sinatra application (http://github.com/njh/dbpedialite/) from ERB to Erubis, but content_for doesn't seem to be working now.

Is sinatra-content-for expected to work with Erubis templates?

Thanks,

nick.

**Comment by foca** [comment]
I never actually tried it, so it's perfectly reasonable to assume it doesn't :)

If you can take a look at how to do it, I'd be most grateful

**Comment by njh** [comment]
Ok, yup. I will try and investigate.

**Comment by akzhan** [comment]
gem install sinatra-content-for2

https://github.com/akzhan/sinatra-content-for2

**Comment by foca** [comment]
Uh, why the name change instead of a pull request? I'm intrigued.

**Comment by akzhan** [comment]
this is because this commit live some months but not pulled into foca's branch.

**Comment by akzhan** [comment]
https://github.com/akzhan/sinatra-content-for2/commit/1902fff07a1889d1c061071fc78dc9f550467537

and some others.
