### ISSUE TITLE
Yank or fix

### ISSUE THREAD

**Issue by tkellen** [foca/sinatra-content-for#5]
Can you please yank or fix this gem?

**Comment by TylerBrock** [comment]
Please! It is extremely annoying that this doesn't work but is included in contrib.

**Comment by foca** [comment]
You should install sinatra-contrib, which includes an updated and
actively maintained content_for implementation, among other things. I
stopped maintaining this once the sinatra team officially took over
with that gem :)

2012/3/15 Tyler Kellen
reply@reply.github.com:

**Comment by foca** [comment]
That said, I yanked the gem and added a reference to Sinatra::Contrib in the README, which is what people should use (unlike sinatra-content-for2, contrib is maintained by the sinatra core team and compatibility is ensured between that and all sinatra versions).

**Comment by TylerBrock** [comment]
Thanks!

**Comment by tkellen** [comment]
Thanks much!
